### ISSUE TITLE
Smart HTTP is causing 'hang-up'

### ISSUE THREAD

**Issue by ghost** [ericpaulbishop/redmine_git_hosting#71]
I seem to have everything setup pretty well, however, SmartHTTP isn't working for me, HTTP or HTTPS.

When I try to clone a url such as redmine-site.com/project.git, I get an error..

```
icearmy@icyplex280:~$ git clone https://User@dev.someurl.com/project.git
Cloning into project...
Password: 
fatal: The remote end hung up unexpectedly
```

I realize I have provided pretty much no information on what the problem could be, but just let me know what you need me to tell you.

So far I can come up with, is my http server domain is exactly the same as the redmine site. I know this is the proper way to do SmartHTTP, but I don't understand how it fails. I can't find any error logs of the problem either.

`Passheader Authorization` did nothing for me either

**Comment by juselius** [comment]
I can confirm this issue. For each attempt I get two lines in access.log, first a 401 "Unauthorized" followed by a 200 "OK", but git tells me that the remote hung up.

"GET /mrcpp.git/info/refs?service=git-upload-pack HTTP/1.1" 401 3481 "-" "git/1.7.4.1"
"GET /mrcpp.git/info/refs?service=git-upload-pack HTTP/1.1" 200 522 "-" "git/1.7.4.1"

**Comment by juselius** [comment]
Running 

wget --ask-password https://user@my.serv.er/proj.git/info/refs?service=git-upload-pack 

gives:

001e# service=git-upload-pack
0000

**Comment by ericpaulbishop** [comment]
Hmm... the second piece of information you (bakerjonas) provide is the really interesting one.  With wget, you seem to be getting the expected output.  This is what you should be seeing from the wget command if everything is working properly.

Is there anything in the repo, or is it empty?  The output is correct for an empty repo (but one that does exist), but not for one that has code in it.

also, are you sure that the version of the git client (as well as the version of git on the server, which the output above indicates is ok) is above 1.6.6?  Older git clients can't handle smart http.

**Comment by ghost** [comment]
My repos all have something in them, yet I am still getting the problem. But even if the repo was empty, shouldn't it still work? Just checking out the empty repo instead (like normal, as it would if I checked it out using SSH).

**Comment by ericpaulbishop** [comment]
Roejames12: It should work (and does work for me...) if there is something in the repositories.  My point above is that the output from: "wget --ask-password https://user@my.serv.er/proj.git/info/refs?service=git-upload-pack" should look exactly like what bakerjonas posted if the repository is empty.  If you run that command on one of your repos, what do you get?

**Comment by ghost** [comment]
I get (again: my repositories are not empty):

```
001e# service=git-upload-pack
0000
```

It might help for you to know that the only thing I'm seeing in my access logs is:

```
xxx.xxx.xx.xx - - [06/Sep/2011:01:13:03 -0700] "GET /project.git/info/refs?service=git-upload-pack HTTP/1.1" 200 4301 "-" "git/1.7.4.1"
```

So I'm not seeing any 401's either, for some reason (when using `https://User@dev.someurl.com/project.git`). I'm getting the same type of thing if I leave out the login `User@` part (which is supposed to be publicly readable by everyone).

**Comment by ericpaulbishop** [comment]
Yeah, that's definitely an error.  I'm not sure where it is though, since I'm having trouble reproducing this problem.  I'll see what I can figure out.

**Comment by ghost** [comment]
The project is public. So the HTTP Url's are supposed to be publicly read-only, and work as read+write when someone authorized is using it. So says the git url display on the project anyways.

Private projects aren't working with this either, however on private projects, it IS sending the 401 for me. However I still get the hangup anyways. That must be why bakerjonas got a 401, because it was a private project.

**Comment by juselius** [comment]
My repositories are most definitively no empty, and cloning over git:// or ssh:// works like a dream. It's just https:// which is causing problems. I have tested with both public read-only and private repositories, and the result is always the same. Authentication works fine, but git-upload-pack fails. I have also played with permissions, but to no avail. My suspicion is that git-upload-pack is run with the wrong path, e.g. $REDMINE_ROOT/public/repositories/proj.git, or something similar. I'll investigate a bit further. Stay tuned!

**Comment by juselius** [comment]
I have tested, and it's not a path problem: Trying to access a non-existent repo gives an error that the repo was not found. Something else is at play here. I have also replicated the problem on yet another server.

Here is the debug output from redmine when trying to access a private repo over https:

Processing GitHttpController#index (for xxx.xxx.xxx.xxx at 2011-09-07 10:50:55) [GET]
  Parameters: {"p1"=>"info", "p2"=>"refs", "p3"=>"", "service"=>"git-upload-pack", "action"=>"index", "id"=>"foobar", "path"=>"foobar.git", "controller"=>"git_http"}
  SQL (0.1ms)   SELECT max(`settings`.updated_on) AS max_updated_on FROM `settings` 
  AnonymousUser Load (0.1ms)   SELECT \* FROM `users` WHERE ( (`users`.`type` = 'AnonymousUser' ) ) LIMIT 1
  Project Load (0.1ms)   SELECT \* FROM `projects` WHERE (`projects`.`identifier` = 'foobar') LIMIT 1
  Repository Load (0.1ms)   SELECT \* FROM `repositories` WHERE (`repositories`.project_id = 55) LIMIT 1
  GitRepositoryExtra Load (0.1ms)   SELECT \* FROM `git_repository_extras` WHERE (`git_repository_extras`.repository_id = 56) LIMIT 1
  Repository Load (0.1ms)   SELECT \* FROM `repositories` WHERE (`repositories`.`id` = 56) 
Filter chain halted as [:authenticate] rendered_or_redirected.
Completed in 6ms (View: 0, DB: 0) | 401 Unauthorized [https://my.serv.er/foobar.git/info/refs?service=git-upload-pack]

Processing GitHttpController#index (for xxx.xxx.xxx.xxx at 2011-09-07 10:50:55) [GET]
  Parameters: {"p1"=>"info", "p2"=>"refs", "p3"=>"", "service"=>"git-upload-pack", "action"=>"index", "id"=>"foobar", "path"=>"foobar.git", "controller"=>"git_http"}
  SQL (0.1ms)   SELECT max(`settings`.updated_on) AS max_updated_on FROM `settings` 
  AnonymousUser Load (0.1ms)   SELECT \* FROM `users` WHERE ( (`users`.`type` = 'AnonymousUser' ) ) LIMIT 1
  Project Load (0.1ms)   SELECT \* FROM `projects` WHERE (`projects`.`identifier` = 'foobar') LIMIT 1
  Repository Load (0.1ms)   SELECT \* FROM `repositories` WHERE (`repositories`.project_id = 55) LIMIT 1
  GitRepositoryExtra Load (0.1ms)   SELECT \* FROM `git_repository_extras` WHERE (`git_repository_extras`.repository_id = 56) LIMIT 1
  Repository Load (0.1ms)   SELECT \* FROM `repositories` WHERE (`repositories`.`id` = 56) 
  User Load (0.1ms)   SELECT \* FROM `users` WHERE (BINARY login = 'myuserid') AND ( (`users`.`type` = 'User' OR `users`.`type` = 'AnonymousUser' ) ) LIMIT 1
  EnabledModule Load (0.1ms)   SELECT name FROM `enabled_modules` WHERE (`enabled_modules`.project_id = 55) 
Completed in 102ms (View: 2, DB: 1) | 200 OK [https://my.serv.er/foobar.git/info/refs?service=git-upload-pack]

**Comment by juselius** [comment]
It's not a permission problem: I'm able to run git-upload-pack as users www-data, redmine and git without any problems. It's tricky to debug, since there is very little information available.

**Comment by ericpaulbishop** [comment]
Can someone who is experiencing this issue please specify (1) The version of sudo being used (2) The exact client version of git and (3) The exact server version of git?

**Comment by juselius** [comment]
1) sudo 1.7.2p1
2) git client  1.7.4.1
3) git server 1.7.0.4

Update: Same problem with sudo 1.7.2.p7 and git 1.7.1.

It does not work with client 1.7.0.4 either. I tested all permissions using sudo, and I was able to access protected files criss cross amongst git and redmine.

**Comment by ghost** [comment]
1) Sudo version 1.7.2p1
2) git version 1.7.4.1
3) git version 1.7.0.4

Funny that we have the exact same versions.

**Comment by juselius** [comment]
Ubuntu 10.04.3 LTS server side, Ubuntu 11.4 client side :)

I'll upgrade the server, and see if it helps!

**Comment by juselius** [comment]
Here is a thing I do not understand, and which might have something to do with the problem: The output from wget for any _existing_ repository with any number of branches is always:

001e# service=git-upload-pack
0000

When running git-upload-pack /path/to/repos/proj.git I get a list of refs and the corresponding name. The _last_ ref is always 0000, and then git-upload-pack hangs until ^C is pressed. Could it be that it's only the last line of output which makes it back to git? That would explain the 0000...

**Comment by juselius** [comment]
Ok, I think I might have managed to get rid of the problem. After a lot of experimentation, it seems the problems have something to do with some configuration of Ubuntu server editon 10.04 LTS and 10.10 . I have really no idea what is going on here, but I installed redmine + git_hosting from scratch on a pristine Ubuntu 11.04 server, copied the repositories over and finally cloned the redmine database, and everything worked! The two machines are running the same version of ruby (give and take a few patch levels), same verison of rails, rack and rake. I then went back to the original server, and completely reinstalled everything (in case some old patches would cause the problems),  and got back to square one: https access does not work. I also tested http access (yes, I enabled http for some projects) over webrick: webrick complained that it could not find the repositories at all. I also tried creating a new project + repository under webrick. Creating the project worked fine, but creating the repo caused webrick to hang (this exposed a new security related bug, which will be in a separate issue). The strange thing is that creating the repo under apache works!  I have no clue how this comes about, but I tested it several times. Tomorrow I'll reinstall the server as 11.04 (due to a grub2 bug, upgrading bricks the server...), and then I'll be able to test https properly.

**Comment by juselius** [comment]
Here is one more clue to anyone trying to tackle this problem: When repository creation hangs under webrick, it seems to be hanging because the command

sh -c /tmp/redmine_git_hosting/run_as_git_user 'echo "[PRIVATE KEY]" > ~/.ssh/gitolite_admin_id_rsa' 

hangs. How that command can hang is beyond me, but it does not complete (that's how I noticed issue #81).

**Comment by ericpaulbishop** [comment]
This should now be fixed.

**Comment by juselius** [comment]
Unfortunately no, the problem is still there.

**Comment by ghost** [comment]
The problem still existed for me, until I restarted my server (which reset the files in /tmp).

**Comment by juselius** [comment]
Bingo, it works! Fantastic! Good job Eric :)

**Comment by ghost** [comment]
I figured that was probably the problem for you. Glad it works now. :)
